### ISSUE TITLE
Safe/Load error

### ISSUE THREAD

**Issue by NiklasVerwey** [WPS/domain-story-modeler#76] opened 2020-02-12 14:04 UTC
**Describe the bug**
We ran into a bug while saving/loading the .dst file. It seems that at some point information of the model is lost. When loading the save file an error message appears and half of the model is gone.
We had the original page still open so we tried multiple times to save with the same result.

**To Reproduce**
The according .dst file is attached (as txt).
[wps_modeler.dst.txt](https://github.com/WPS/domain-story-modeler/files/4192689/wps_modeler.dst.txt)

1. Go to www.wps.de/modeler
2. Click on import file
3. Select the attached .dst file
4. See error message

**Screenshots**
This is how it should look:
![image](https://user-images.githubusercontent.com/60971646/74339624-bf703a80-4da4-11ea-985d-d51910dd3ee2.png)

This is the error:
![image](https://user-images.githubusercontent.com/60971646/74340696-aa94a680-4da6-11ea-8417-62497f8b4748.png)

This is how it looks:
![image](https://user-images.githubusercontent.com/60971646/74340740-c5ffb180-4da6-11ea-98cf-c5fb80c9ed29.png)

**Desktop:**
 - Modeler Version: v1.0.0
 - Browser: Chrome 79.0.3945.130 64Bit
 - OS: Windows 10

**Additional context**
It seems that the browserversion or the project itself is causing the error. We worked with another browser (Chrome 80.0.3987.100) on a different project and hat no problems.

**Comment by HaukeStieler-WPS** [comment] 2020-03-10 17:10
Thanks for reporting the issue.

I was able to reproduce the error you reported. The missing "Verkäufer" and "Ticket" are causing the error, because the modeler can't create the connections between them. I also looked at the dst file you provided and these two nodes are missing there as well. That means the error is in the export rather than the import function. I also tested it on Chrome (version 80.0.3987.137) but the error occurred there as well.

I re-added these two missing nodes and the missing connections, exported the project, imported it and everything was working fine.

I know it's a long time ago but do you know if you were doing something during export or right before it? Otherwise it's very hard to reproduce the faulty export.

**Comment by hofstef** [comment] 2021-05-06 12:30
Since this was reported for v1.0.0 and we have since release several new version, I will close this ticket. Please let us know if any other issues with import/export come up.

**Closed by hofstef** 2021-05-06 12:30 UTC
Labels: bug
