### ISSUE TITLE
Undo of inserting Context Box removes linked actor

### ISSUE THREAD

**Issue by nilsbert** [WPS/domain-story-modeler#85] opened 2020-09-17 08:58 UTC
**Describe the bug**
Undo of inserting Context Box removes linked actor.

**To Reproduce**
1. Insert icon "mobile phone"
2. Insert icon actor
3. Link mobile phone to actor
4. Repeat it for other element -> Screenshot
5. Draw context box fully over linked elements
6. Undo -> Strg Z
7. Box and some icons are removed

**Expected behavior**
Only box removed

**Screenshots**
<img width="730" alt="Bildschirmfoto 2020-09-17 um 10 54 13" src="https://user-images.githubusercontent.com/3332709/93448907-69ccb500-f8d4-11ea-88e0-efa7b1053a57.png">

<img width="658" alt="Bildschirmfoto 2020-09-17 um 10 55 05" src="https://user-images.githubusercontent.com/3332709/93448904-69341e80-f8d4-11ea-982b-8f323e823c54.png">

**Command-Z**

<img width="735" alt="Bildschirmfoto 2020-09-17 um 10 55 10" src="https://user-images.githubusercontent.com/3332709/93448901-6802f180-f8d4-11ea-8ee8-77976487c12a.png">

[If applicable, add screenshots to help explain your problem.]

**Desktop + Browser:**
MacOs: 10.15.6
Chrome: Version 85.0.4183.102 (Offizieller Build) (64-Bit)

**Comment by hofstef** [comment] 2020-10-13 09:32
Hi, if I follow your steps, I cannot reproduce the problem (Modeler v1.1.1). However, I noticed that your screenshots do not match the steps you described. Could you please check if the steps that you provided are describing the incorrect behavour? Thanks!

**Comment by hofstef** [comment] 2021-03-09 21:19
fixed in v1.2.0

**Closed** 2021-03-09 21:19 UTC
Labels: bug
